[tool.poetry]
name = "ocr-backend"
version = "0.1.0"
description = "Backend for OCR"
authors = ["Ahmed-Mohiuddin-Shah <mohiuddinlive@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.10.0.84"
psycopg2 = "^2.9.9"
python-decouple = "^3.8"
paddlepaddle = "^2.6.1"
paddleocr = "^2.8.0"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
